JumpsellerSync/JumpsellerSync.RestApi.Frontend/Controllers/LocalProductController.cs
using AutoMapper;

using JumpsellerSync.BusinessLogic.Core.Dtos;
using JumpsellerSync.BusinessLogic.Core.Extensions;
using JumpsellerSync.BusinessLogic.Core.Services.Main;
using JumpsellerSync.RestApi.Core.Controllers;
using JumpsellerSync.RestApi.FrontEnd.Models;

using Microsoft.AspNetCore.Mvc;

using System.Linq;
using System.Threading.Tasks;

namespace JumpsellerSync.RestApi.FrontEnd.Controllers
{
    public class LocalProductController : BaseController
    {
        private readonly ILocalProductService localProductService;
        private readonly IProductService productService;
        private readonly IMapper mapper;

        public LocalProductController(
            ILocalProductService localProductService,
            IProductService productService,
            IMapper mapper)
        {
            this.localProductService = localProductService;
            this.productService = productService;
            this.mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var brandsResult = await productService.PrefetchBrandsAsync();

            return brandsResult.IsSucceed()
                ? View(brandsResult.Data)
                : FromServiceResult(brandsResult);
        }

        [HttpGet]
        public async Task<IActionResult> Products([FromQuery] ReadPageDto q)
        {
            if (IsAjaxRequest)
            {
                var page = await localProductService.ReadAsync(default, q.Page, q.Limit);

                ViewBag.TotalPages = page.TotalPages;
                return page.Items.Count() == 0
                    ? (IActionResult)Content("")
                    : PartialView(page.Items);
            }

            return BadRequest();
        }

        [HttpGet]
        public async Task<IActionResult> SyncedProducts([FromQuery] SearchSyncedProductsViewModel q)
        {
            if (IsAjaxRequest)
            {
                var products = await localProductService.SearchSyncedProductsAsync(
                    q?.BrandId, q?.SkuOrName, q?.Limit ?? 10);

                return products.Count() == 0
                    ? (IActionResult)Content("")
                    : PartialView(products);

            }
            return BadRequest();
        }

        [HttpPost]
        public async Task<IActionResult> Create([FromBody] CreateLocalProductsViewModel body)
        {
            if (ModelState.IsValid)
            {
                var result = await localProductService.CreateAsync(body.Products);
                return FromServiceResult(result);
            }
            return BadRequest();
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            var readLocalProductResult = await localProductService.ReadAsync(id);

            return readLocalProductResult.IsSucceed()
                ? View(readLocalProductResult.Data)
                : FromServiceResult(readLocalProductResult);
        }

        [HttpPost]
        public async Task<IActionResult> ConfirmDelete([FromForm] string id)
        {
            var deleteResult = await localProductService.DeleteAsync(id);
            return deleteResult.IsSucceed()
                ? RedirectToAction(nameof(Index))
                : FromServiceResult(deleteResult);
        }

        [HttpPut]
        public async Task<IActionResult> Update([FromBody] UpdateLocalProductsViewModel body)
        {
            if (ModelState.IsValid)
            {
                var updateResult = await localProductService.UpdateAsync(body.Products);
                return FromServiceResult(updateResult);
            }

            return BadRequest();
        }
    }
}

JumpsellerSync/JumpsellerSync.RestApi.Frontend/Controllers/ProductController.cs
using AutoMapper;

using JumpsellerSync.BusinessLogic.Core.Dtos.Main;
using JumpsellerSync.BusinessLogic.Core.Dtos.Provider;
using JumpsellerSync.BusinessLogic.Core.Extensions;
using JumpsellerSync.BusinessLogic.Core.Services.Main;
using JumpsellerSync.RestApi.Core.Controllers;
using JumpsellerSync.RestApi.FrontEnd.Models;

using Microsoft.AspNetCore.Mvc;

using System.Linq;
using System.Threading.Tasks;

namespace JumpsellerSync.RestApi.FrontEnd.Controllers
{
    public class ProductController : BaseController
    {
        private readonly IProviderService providerService;
        private readonly IProductService productService;
        private readonly IMapper mapper;

        public ProductController(
            IProviderService providerService,
            IProductService productService,
            IMapper mapper)
        {
            this.providerService = providerService;
            this.productService = productService;
            this.mapper = mapper;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var providers = await providerService.ReadActiveProvidersAsync();

            return View(providers);
        }

        [HttpGet]
        public async Task<IActionResult> PrefetchBrands()
        {
            if (IsAjaxRequest)
            {
                var brands = await productService.PrefetchBrandsAsync();
                return Json(brands.Data);
            }

            return BadRequest();
        }

        [HttpGet]
        public async Task<IActionResult> SkuOrNameProductSuggestions(
            [FromQuery] ReadProductSuggestionsViewModel q)
        {
            if (IsAjaxRequest)
            {
                var suggestionsResult = q.SyncedProducts
                    ? await productService.ReadProductSuggestionsAsync(
                        mapper.Map<ReadProductSuggestionsDto>(q))
                    : await providerService.ReadProductSuggestionsAsync(
                        mapper.Map<ReadProviderProductSuggestionsDto>(q));

                return Json(suggestionsResult);
            }
            return BadRequest();
        }

        [HttpGet]
        public async Task<IActionResult> UnsyncedProducts(
            [FromQuery] LoadUnsyncedProductsPageViewModel q)
        {
            if (IsAjaxRequest && ModelState.IsValid)
            {
                var page =
                    await providerService.ReadProductsAsync(mapper.Map<SearchUnsyncedProductsDto>(q));
                ViewBag.TotalPages = page.TotalPages;

                return page.Items.Count() == 0
                    ? (IActionResult)Content("")
                    : PartialView(page.Items);
            }

            return BadRequest();
        }

        [HttpGet]
        public async Task<IActionResult> SyncedProducts([FromQuery] LoadSyncedProductsPageViewModel q)
        {
            if (IsAjaxRequest)
            {
                var page = await productService.ReadAsync(mapper.Map<SearhProductsDto>(q));
                ViewBag.TotalPages = page.TotalPages;

                return page.Items.Count() == 0
                    ? (IActionResult)Content("")
                    : PartialView(page.Items);

            }
            return BadRequest();
        }

        [HttpPost]
        public async Task<IActionResult> SyncProduct(
            [FromBody] CreateProductDto data)
        {
            if (ModelState.IsValid)
            {
                var result = await productService.CreateAsync(data);
                return FromServiceResult(result);
            }

            return BadRequest();
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            var productResult = await productService.ReadAsync(id);
            return productResult.IsSucceed()
                ? View(productResult.Data)
                : FromServiceResult(productResult);
        }

        [HttpPost]
        public async Task<IActionResult> Edit([FromForm] ProductDetailsDto product)
        {
            if (!ModelState.IsValid)
            { return View(product); }
            var updateResult = await productService.UpdateMarginAsync(product);
            return updateResult.IsSucceed()
                ? RedirectToAction("Index")
                : FromServiceResult(updateResult);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            var productResult = await productService.ReadAsync(id);
            return productResult.IsSucceed()
                ? View(productResult.Data)
                : FromServiceResult(productResult);
        }

        [HttpPost]
        public async Task<IActionResult> ConfirmDelete([FromForm] string id)
        {
            var unsyncAsync = await productService.DeleteAsync(id);
            return unsyncAsync.IsSucceed()
                ? RedirectToAction("Index")
                : FromServiceResult(unsyncAsync);
        }
    }
}

JumpsellerSync/JumpsellerSync.RestApi.Frontend/Controllers/ProviderController.cs
using JumpsellerSync.BusinessLogic.Core.Dtos.Main;
using JumpsellerSync.BusinessLogic.Core.Extensions;
using JumpsellerSync.BusinessLogic.Core.Services.Main;
using JumpsellerSync.RestApi.Core.Controllers;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace JumpsellerSync.RestApi.FrontEnd.Controllers
{
    public class ProviderController : BaseController
    {
        private readonly IProviderService providerService;
        private readonly ISynchronizeProvidersService synchronizeProvidersService;

        public ProviderController(
            IProviderService providerService,
            ISynchronizeProvidersService synchronizeProvidersService)
        {
            this.providerService = providerService;
            this.synchronizeProvidersService = synchronizeProvidersService;
        }

        public async Task<IActionResult> Index()
        {
            var providers = await providerService.ReadProvidersAsync();

            return View(providers);
        }

        public async Task<IActionResult> Brands([FromQuery] string providerId)
        {
            var brands = await providerService.ReadProviderBrandsAsync(providerId);

            if (IsAjaxRequest)
            {
                return brands.Count() == 0
                    ? (IActionResult)Content("")
                    : PartialView(brands);
            }

            return BadRequest();
        }

        [HttpPost]
        public async Task<IActionResult> Sync(string id)
        {
            var syncResult =
                await synchronizeProvidersService.SynchronizeProviderAsync(id);

            return FromServiceResult(syncResult);
        }

        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.ProviderTypes = ProviderTypes(ProviderType.HourlyProvider);
            return View(
                new ProviderDto
                {
                    Active = true,
                    ProviderType = ProviderType.HourlyProvider,
                    Priority = 1,
                    Interval = 2,
                    Hours = new List<string> { "07:00", "19:00" },
                    StartTime = "19:00"
                });
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm] ProviderDto provider)
        {
            if (ModelState.IsValid)
            {
                var createResult = await providerService.CreateAsync(provider);
                if (createResult.IsSucceed())
                { return RedirectToAction("Index"); }

                ModelState.AddModelError("", "Ha ocurrido un error mientras se creaba el proveedor.");
            }

            ConfigBadProviderInput(provider);
            return View(provider);
        }

        [HttpGet]
        public async Task<IActionResult> Edit(string id)
        {
            var readResult = await providerService.ReadAsync(id);
            if (readResult.IsSucceed())
            {
                var provider = readResult.Data;
                ViewBag.ProviderTypes = ProviderTypes(provider.ProviderType);
                return View(provider);
            }
            return FromServiceResult(readResult);
        }

        [HttpPost, ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromForm] ProviderDto provider)
        {
            if (ModelState.IsValid)
            {
                var createResult = await providerService.UpdateAsync(provider);
                if (createResult.IsSucceed())
                { return RedirectToAction("Index"); }

                ModelState.AddModelError("", "Ha ocurrido un error mientras se actualizaba el proveedor.");
            }

            ConfigBadProviderInput(provider);
            return View(provider);
        }

        private void ConfigBadProviderInput(ProviderDto provider)
        {
            AddHoursError();
            if (!Enum.IsDefined(typeof(ProviderType), provider.ProviderType))
            { provider.ProviderType = ProviderType.HourlyProvider; }
            ViewBag.ProviderTypes = ProviderTypes(provider.ProviderType);
        }

        private static List<SelectListItem> ProviderTypes(ProviderType selected)
            => new List<SelectListItem>
            {
                new SelectListItem(
                    "Periódica",
                    ((int)ProviderType.PeriodicallyProvider).ToString(),
                    selected == ProviderType.PeriodicallyProvider),
                new SelectListItem(
                    "Por horas",
                    ((int)ProviderType.HourlyProvider).ToString(),
                    selected == ProviderType.HourlyProvider),
            };

        private void AddHoursError()
        {
            var p = nameof(ProviderDto.Hours);
            if (ModelState
                    .FindKeysWithPrefix(p)
                    .Where(kv => Regex.IsMatch(kv.Key, $@"{p}\[\d+\]"))
                    .Where(kv => kv.Value.Errors.Count > 0)
                    .Count() > 0)
            {
                ModelState.AddModelError(
                    nameof(ProviderDto.Hours),
                    "El formato de las horas es 23:59.");
            }
        }
    }
}

JumpsellerSync/JumpsellerSync.RestApi.Frontend/Views/Shared/_Layout.cshtml
@{
   var appName = "Sincroniza Proveedores";
}

<!DOCTYPE html>
<html lang="en">
<head>
   <meta charset="utf-8" />
   <meta name="viewport" content="width=device-width, initial-scale=1.0" />
   <title>@ViewData["Title"] - @appName</title>

   <link rel="stylesheet"
         href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
   <environment include="Development">
      <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
      <link rel="stylesheet" href="~/css/site.css" />
   </environment>
   <environment exclude="Development">
      <link rel="stylesheet" href="~/bundles/css/site.min.css" />
   </environment>

   @RenderSection("Styles", false)

</head>
<body>
   <header>
      <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
         <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@appName</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
               <span class="navbar-toggler-icon">
                  <i class="fa fa-3 fa-bars" aria-label="hidden" style="font-size: 1.7rem;"></i>
               </span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
               <ul class="navbar-nav flex-grow-1">
                  <li class="nav-item">
                     <a class="nav-link text-dark"
                        asp-area=""
                        asp-controller="Product"
                        asp-action="Index">
                        Productos
                     </a>
                  </li>
                   <li class="nav-item">
                     <a class="nav-link text-dark"
                        asp-area=""
                        asp-controller="LocalProduct"
                        asp-action="Index">
                        Productos Locales
                     </a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link text-dark"
                        asp-area=""
                        asp-controller="Provider"
                        asp-action="Index">
                        Proveedores
                     </a>
                  </li>
                  <li class="nav-item">
                     <a class="nav-link text-dark"
                        asp-area=""
                        asp-controller="Manage"
                        asp-action="Index">
                        Administrar
                     </a>
                  </li>
               </ul>
            </div>
         </div>
      </nav>
   </header>
   <div class="container">
      <main role="main" class="pb-3">
         @RenderBody()
      </main>
   </div>

   <footer class="border-top footer text-muted">
      <div class="container">
         &copy; 2020 - @appName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
      </div>
   </footer>

   <div id="alerts-container">
      <div id="ui-alerts">

      </div>
   </div>

   <environment include="Development">
      <script src="~/lib/jquery/dist/jquery.js"></script>
      <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
      <script src="~/js/site.js"></script>
   </environment>
   <environment exclude="Development">
      <script src="~/bundles/js/site.min.js"></script>
   </environment>

   @RenderSection("Scripts", required: false)

</body>
</html>